version: '3.0'

services:

  frontend:
    image: nginx:latest
    ports:
      - "20080:80"
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - php-frontend
  backend:
    image: nginx:latest
    ports:
      - "20081:80"
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - php-backend
  php-frontend:
    image: gao922699/php5.6-fpm-personal
    tty: true
    volumes:
      - ./:/var/www/html
  php-backend:
    image: gao922699/php5.6-fpm-personal
    tty: true
    volumes:
      - ./:/var/www/html